# Welcome to Jekyll!
#

# Site settings
title: Welcome | YoungWoong Cho
description: 
  Welcome to my homepage. You can view my resume and portfolio from this site. Want to know more of me? Feel free to contact!
owner: YoungWoong Cho
first_published: 2020 # if migrating another site, the year of your first publish
email: herocho1997@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://youngwoong-cho.github.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/youngwoong-cho
  linkedin-square: https://www.linkedin.com/in/youngwoong-cho-09b587197/
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: herocho1997@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
# markdown: kramdown
#sass:
#  style: compressed
